### ISSUE TITLE
リソースツリーポップアップでの公開／非公開

### ISSUE THREAD

**Issue by Fiberalph** [modxcms-jp/evolution-jp#124]
表題の件で検討

リソースツリーのリソース右クリックで現れるポップアップメニューの、
公開／非公開では、実行時に管理操作ログに、
[61] Publishing a resource
[62] Un-publishing a resource
は登録されるが、
[27] Editing resource
も登録されるようにするかどうか？

また、逆でも同じように、リソースの編集時にリソース変数「公開ステータス」の変更によって、
[61] Publishing a resource
[62] Un-publishing a resource
が管理操作ログに登録されるようにするかどうか？

**Comment by yama** [comment]
記録されるようにしたほうがいいと思います

**Comment by Fiberalph** [comment]
ツリーメニューの公開／非公開で、リソースの更新時刻も更新する。
