### ISSUE TITLE
プレースホルダの中の文字列に閉じカッコ　「)」　が入っていた場合、そこでPhxのモディファイアが終わってしまう

### ISSUE THREAD

**Issue by teruringo** [modxcms-jp/evolution-jp#129]
`[*hogehoge:ifnotempty(<div>[*hogehoge*]</div>)*]`
っていうような感じの書き方をしたんですが、
hogehogeの中に閉じカッコが入っているとそこで終わってしまうらしく、表示がバグってしまいました。

という報告です！

**Comment by Fiberalph** [comment]
ifnotempty()内をクォーテーションで囲ってみてください。

**Comment by teruringo** [comment]
解決しました！ありがとうございます。（閉じ忘れ）
