### ISSUE TITLE
MySQLを廃止してMySQLiを使用する。

### ISSUE THREAD

**Issue by Fiberalph** [modxcms-jp/evolution-jp#143]
幾つか進めているようですが、本気で進めてもよろしいでしょうか？

**Comment by yama** [comment]
ファーストサーバで動作しない事例(PHP5.3だがmysqli関数が使えない)があるようです。後ほど調整します

**Comment by Fiberalph** [comment]
1.0.15Jで対応済みを確認しました。
ありがとうございました(_ _)
