### ISSUE TITLE
DittoにouterTplパラメータの追加

### ISSUE THREAD

**Issue by soushi** [modxcms-jp/evolution-jp#159]
Dittoの出力が0件だった時に外部のHTMLの出力を制限するためのouterTplパラメータを実装する。

使い方例。
```
[[Ditto
  &outTpl='<table>[+output+]</table>'
  &noResults=''
]]
```

Dittoの出力がない、かつnoResultsが空白の場合は`<table>`タグも含めて出力しなくなる…という感じ。

ところでDittoの現在の開発元ってどこになるんでしょうか…もうMODX Japan内で適当に変更していってもいいのでしょうか。

**Comment by yama** [comment]
このパラメータはウクライナのドミトリーが実装した気がします。&outertplか&tplouterだったと思います

**Comment by soushi** [comment]
おおーソース見たらなんか書いてました。&tplOuterがパラメータ名みたいです。
もうDittoのおおもとの開発元ってないですかね…軽く調べてみたのですが見つからず。
もしgithubにリポジトリがあればそこからフォームするのもありかなと思ったのですが。

今後なにか修正したい事があれば直接 modx-jp 側にコミットするようにします。

**Comment by yama** [comment]
Dittoは古いスニペット扱いなので開発者は特に気にしなくてもよさそうに思います。本家版も調整程度しか手を入れてませんし

**Comment by soushi** [comment]
了解ですー。
とりあえず今回は既に機能が実装されていたので、こちらはクローズしちゃいます。
